/* Do not edit this file. It is produced from the corresponding .m4 source */
/*
 *  Copyright (C) 2021, Northwestern University and Argonne National Laboratory
 *  See COPYRIGHT notice in top-level directory.
 */
/* $Id$ */


#ifdef HAVE_CONFIG_H
# include <config.h>
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <mpi.h>

#include <pnc_debug.h>
#include <common.h>
#include <ncchkio_driver.h>
#include "ncchkio_internal.h"
#include "ncchkioi_profile.h"

/*
 * Report performance profiling
 */
#ifdef PNETCDF_PROFILING

static double tmax[NC_CHK_NTIMER], tmin[NC_CHK_NTIMER], tmean[NC_CHK_NTIMER], tvar[NC_CHK_NTIMER], tvar_local[NC_CHK_NTIMER];

const char * const tname[NC_CHK_NTIMER]={
"nc_chk_timer_total",
"nc_chk_timer_var_init",
"nc_chk_timer_var_init_meta",
"nc_chk_timer_var_init_csize",
"nc_chk_timer_var_init_cown",
"nc_chk_timer_var_resize",
"nc_chk_timer_put",
"nc_chk_timer_put_cb",
"nc_chk_timer_put_cb_init",
"nc_chk_timer_put_cb_sync",
"nc_chk_timer_put_cb_pack_req",
"nc_chk_timer_put_cb_pack_rep",
"nc_chk_timer_put_cb_unpack_req",
"nc_chk_timer_put_cb_unpack_rep",
"nc_chk_timer_put_cb_send_req",
"nc_chk_timer_put_cb_send_rep",
"nc_chk_timer_put_cb_recv_req",
"nc_chk_timer_put_cb_recv_rep",
"nc_chk_timer_put_cb_self",
"nc_chk_timer_put_cb_barr",
"nc_chk_timer_put_bg",
"nc_chk_timer_put_bg_init",
"nc_chk_timer_put_bg_cache",
"nc_chk_timer_put_bg_rd",
"nc_chk_timer_put_bg_decom",
"nc_chk_timer_put_io",
"nc_chk_timer_put_io_init",
"nc_chk_timer_put_io_com",
"nc_chk_timer_put_io_sync",
"nc_chk_timer_put_io_wr",
"nc_chk_timer_put_io_barr",
"nc_chk_timer_get",
"nc_chk_timer_get_resize",
"nc_chk_timer_get_cb",
"nc_chk_timer_get_cb_init",
"nc_chk_timer_get_cb_sync",
"nc_chk_timer_get_cb_pack_req",
"nc_chk_timer_get_cb_pack_rep",
"nc_chk_timer_get_cb_unpack_req",
"nc_chk_timer_get_cb_unpack_rep",
"nc_chk_timer_get_cb_send_req",
"nc_chk_timer_get_cb_send_rep",
"nc_chk_timer_get_cb_recv_req",
"nc_chk_timer_get_cb_recv_rep",
"nc_chk_timer_get_cb_self",
"nc_chk_timer_get_cb_barr",
"nc_chk_timer_get_io",
"nc_chk_timer_get_io_init",
"nc_chk_timer_get_io_cache",
"nc_chk_timer_get_io_rd",
"nc_chk_timer_get_io_decom",
"nc_chk_timer_get_convert",
"nc_chk_timer_finalize",
"nc_chk_timer_finalize_meta",
"nc_chk_timer_iput",
"nc_chk_timer_iget",
"nc_chk_timer_wait",
"nc_chk_timer_wait_put",
"nc_chk_timer_wait_put_barr",
"nc_chk_timer_wait_get",
"nc_chk_timer_put_size",
"nc_chk_timer_get_size",
"nc_chk_timer_send_size",
"nc_chk_timer_recv_size",
"nc_chk_timer_nsend",
"nc_chk_timer_nrecv",
"nc_chk_timer_nremote",
"nc_chk_timer_nreq",
"nc_chk_timer_nlocal",
"nc_chk_timer_nchunk",
"nc_chk_timer_var_size",
"nc_chk_timer_var_zsize",
};

void ncchkioi_profile_add_time (NC_chk *ncchkp, int id, double t) {
	assert (id >= 0 && id < NC_CHK_NTIMER);
	ncchkp->profile.tt[id] += t;
	ncchkp->profile.cnt[id]++;
}

void ncchkioi_print_profile(NC_chk *ncchkp){
    int i;

	MPI_Reduce (ncchkp->profile.tt, tmax, NC_CHK_NTIMER, MPI_DOUBLE, MPI_MAX, 0, ncchkp->comm);
	MPI_Reduce (ncchkp->profile.tt, tmin, NC_CHK_NTIMER, MPI_DOUBLE, MPI_MIN, 0, ncchkp->comm);
	MPI_Allreduce (ncchkp->profile.tt, tmean, NC_CHK_NTIMER, MPI_DOUBLE, MPI_SUM, ncchkp->comm);
	for (i = 0; i < NC_CHK_NTIMER; i++) {
		tmean[i] /= ncchkp->np;
		tvar_local[i] = (ncchkp->profile.tt[i] - tmean[i]) * (ncchkp->profile.tt[i] - tmean[i]);
	}
	MPI_Reduce (tvar_local, tvar, NC_CHK_NTIMER, MPI_DOUBLE, MPI_SUM, 0, ncchkp->comm);

	if (ncchkp->rank == 0) {
		for (i = 0; i < NC_CHK_NTIMER; i++) {
			printf ("#%%$: %s_time_mean: %lf\n", tname[i], tmean[i]);
			printf ("#%%$: %s_time_max: %lf\n", tname[i], tmax[i]);
			printf ("#%%$: %s_time_min: %lf\n", tname[i], tmin[i]);
			printf ("#%%$: %s_time_var: %lf\n\n", tname[i], tvar[i]);
		}
	}

	MPI_Reduce (ncchkp->profile.cnt, tmax, NC_CHK_NTIMER, MPI_DOUBLE, MPI_MAX, 0, ncchkp->comm);
	MPI_Reduce (ncchkp->profile.cnt, tmin, NC_CHK_NTIMER, MPI_DOUBLE, MPI_MIN, 0, ncchkp->comm);
	MPI_Allreduce (ncchkp->profile.cnt, tmean, NC_CHK_NTIMER, MPI_DOUBLE, MPI_SUM, ncchkp->comm);
	for (i = 0; i < NC_CHK_NTIMER; i++) {
		tmean[i] /= ncchkp->np;
		tvar_local[i] = (ncchkp->profile.cnt[i] - tmean[i]) * (ncchkp->profile.cnt[i] - tmean[i]);
	}
	MPI_Reduce (tvar_local, tvar, NC_CHK_NTIMER, MPI_DOUBLE, MPI_SUM, 0, ncchkp->comm);

	if (ncchkp->rank == 0) {
		for (i = 0; i < NC_CHK_NTIMER; i++) {
			printf ("#%%$: %s_count_mean: %lf\n", tname[i], tmean[i]);
			printf ("#%%$: %s_count_max: %lf\n", tname[i], tmax[i]);
			printf ("#%%$: %s_count_min: %lf\n", tname[i], tmin[i]);
			printf ("#%%$: %s_count_var: %lf\n\n", tname[i], tvar[i]);
		}
	}          
}
#endif




