/* Do not edit this file. It is produced from the corresponding .m4 source */
/*
 *  Copyright (C) 2021, Northwestern University and Argonne National Laboratory
 *  See COPYRIGHT notice in top-level directory.
 */
/* $Id$ */


#pragma once

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

/*
 * Report performance profiling
 */
#ifdef PNETCDF_PROFILING

#define NC_CHK_NTIMER 72

#define NC_CHK_TIMER_TOTAL 0
#define NC_CHK_TIMER_VAR_INIT 1
#define NC_CHK_TIMER_VAR_INIT_META 2
#define NC_CHK_TIMER_VAR_INIT_CSIZE 3
#define NC_CHK_TIMER_VAR_INIT_COWN 4
#define NC_CHK_TIMER_VAR_RESIZE 5
#define NC_CHK_TIMER_PUT 6
#define NC_CHK_TIMER_PUT_CB 7
#define NC_CHK_TIMER_PUT_CB_INIT 8
#define NC_CHK_TIMER_PUT_CB_SYNC 9
#define NC_CHK_TIMER_PUT_CB_PACK_REQ 10
#define NC_CHK_TIMER_PUT_CB_PACK_REP 11
#define NC_CHK_TIMER_PUT_CB_UNPACK_REQ 12
#define NC_CHK_TIMER_PUT_CB_UNPACK_REP 13
#define NC_CHK_TIMER_PUT_CB_SEND_REQ 14
#define NC_CHK_TIMER_PUT_CB_SEND_REP 15
#define NC_CHK_TIMER_PUT_CB_RECV_REQ 16
#define NC_CHK_TIMER_PUT_CB_RECV_REP 17
#define NC_CHK_TIMER_PUT_CB_SELF 18
#define NC_CHK_TIMER_PUT_CB_BARR 19
#define NC_CHK_TIMER_PUT_BG 20
#define NC_CHK_TIMER_PUT_BG_INIT 21
#define NC_CHK_TIMER_PUT_BG_CACHE 22
#define NC_CHK_TIMER_PUT_BG_RD 23
#define NC_CHK_TIMER_PUT_BG_DECOM 24
#define NC_CHK_TIMER_PUT_IO 25
#define NC_CHK_TIMER_PUT_IO_INIT 26
#define NC_CHK_TIMER_PUT_IO_COM 27
#define NC_CHK_TIMER_PUT_IO_SYNC 28
#define NC_CHK_TIMER_PUT_IO_WR 29
#define NC_CHK_TIMER_PUT_IO_BARR 30
#define NC_CHK_TIMER_GET 31
#define NC_CHK_TIMER_GET_RESIZE 32
#define NC_CHK_TIMER_GET_CB 33
#define NC_CHK_TIMER_GET_CB_INIT 34
#define NC_CHK_TIMER_GET_CB_SYNC 35
#define NC_CHK_TIMER_GET_CB_PACK_REQ 36
#define NC_CHK_TIMER_GET_CB_PACK_REP 37
#define NC_CHK_TIMER_GET_CB_UNPACK_REQ 38
#define NC_CHK_TIMER_GET_CB_UNPACK_REP 39
#define NC_CHK_TIMER_GET_CB_SEND_REQ 40
#define NC_CHK_TIMER_GET_CB_SEND_REP 41
#define NC_CHK_TIMER_GET_CB_RECV_REQ 42
#define NC_CHK_TIMER_GET_CB_RECV_REP 43
#define NC_CHK_TIMER_GET_CB_SELF 44
#define NC_CHK_TIMER_GET_CB_BARR 45
#define NC_CHK_TIMER_GET_IO 46
#define NC_CHK_TIMER_GET_IO_INIT 47
#define NC_CHK_TIMER_GET_IO_CACHE 48
#define NC_CHK_TIMER_GET_IO_RD 49
#define NC_CHK_TIMER_GET_IO_DECOM 50
#define NC_CHK_TIMER_GET_CONVERT 51
#define NC_CHK_TIMER_FINALIZE 52
#define NC_CHK_TIMER_FINALIZE_META 53
#define NC_CHK_TIMER_IPUT 54
#define NC_CHK_TIMER_IGET 55
#define NC_CHK_TIMER_WAIT 56
#define NC_CHK_TIMER_WAIT_PUT 57
#define NC_CHK_TIMER_WAIT_PUT_BARR 58
#define NC_CHK_TIMER_WAIT_GET 59
#define NC_CHK_TIMER_PUT_SIZE 60
#define NC_CHK_TIMER_GET_SIZE 61
#define NC_CHK_TIMER_SEND_SIZE 62
#define NC_CHK_TIMER_RECV_SIZE 63
#define NC_CHK_TIMER_NSEND 64
#define NC_CHK_TIMER_NRECV 65
#define NC_CHK_TIMER_NREMOTE 66
#define NC_CHK_TIMER_NREQ 67
#define NC_CHK_TIMER_NLOCAL 68
#define NC_CHK_TIMER_NCHUNK 69
#define NC_CHK_TIMER_VAR_SIZE 70
#define NC_CHK_TIMER_VAR_ZSIZE 71

#define NC_CHK_TIMER_START(A) ncchkp->profile.st[A] = MPI_Wtime(); 
#define NC_CHK_TIMER_PAUSE(A)  { \
    ncchkp->profile.tt[A] += MPI_Wtime() - ncchkp->profile.st[A]; \
}
#define NC_CHK_TIMER_STOP(A)  { \
    NC_CHK_TIMER_PAUSE(A) \
    ncchkp->profile.cnt[A] ++; \
}
#define NC_CHK_TIMER_SWAP(A, B)  { \
    double tmp = MPI_Wtime(); \
    ncchkp->profile.tt[A] += tmp - ncchkp->profile.st[A]; \
    ncchkp->profile.cnt[A] ++; \
    ncchkp->profile.st[B] = tmp;  \
}
#define NC_CHK_TIMER_STOPEX(A, B)  { \
    double tmp = MPI_Wtime(); \
    ncchkp->profile.tt[A] += tmp - ncchkp->profile.st[A]; \
    ncchkp->profile.cnt[A] ++; \
    ncchkp->profile.tt[B] -= tmp - ncchkp->profile.st[A]; \
}

typedef struct NC_chk_timers {
    /* Profiling information */
    double st[NC_CHK_NTIMER];
    double tt[NC_CHK_NTIMER];
    double cnt[NC_CHK_NTIMER];
} NC_chk_timers;

#else

#define NC_CHK_TIMER_START(A)
#define NC_CHK_TIMER_STOP(A)
#define NC_CHK_TIMER_PAUSE(A)
#define NC_CHK_TIMER_SWAP(A, B)
#define NC_CHK_TIMER_STOPEX(A, B) 

#endif

